-
  branches:
    only:
      - master
  version: 2.0.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  image: Visual Studio 2019
  clone_depth: 1
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  build_script:
  - cmd: dotnet build -c Release -v minimal src\Credentials.sln
  after_build:
  - cmd: dotnet pack -v minimal --include-symbols --no-build src\Credentials/Credentials.csproj
  test:
    assemblies:
      - '**\UnitTests.dll'
  deploy:
  - provider: NuGet
    symbol_server: https://api.nuget.org/v3/index.json
    api_key:
      secure: JIXBuXT5w3Xu82NM/mUdzwp+bM0iXMtuF5ZCnrAwuMsqeAthe1jxsqKCVWXzGOxt
    artifact: /.*\.s?nupkg/
-
  version: 2.0.0.{build} 
  pull_requests:
    do_not_increment_build_number: true
  image: Visual Studio 2019
  clone_depth: 1
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  build_script:
  - cmd: dotnet build -c Release -v minimal src\Credentials.sln
  after_build:
  - cmd: dotnet pack -v minimal --include-symbols --no-build src\Credentials/Credentials.csproj
  test:
    assemblies:
      - '**\UnitTests.dll'